apiVersion: v1
kind: Pod
metadata:
  name: emp-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr 
      image: 10542/employeeimg:employeek8simg
      ports:
        - containerPort: 8085